# Netplan: 2 bridges, 2 subnets (IPv4 only)
# Replace placeholders: IFACE0, IFACE1, PUBLIC_IP, PUBLIC_CIDR, PUBLIC_GW,
#                        SUBNET2_IP, SUBNET2_CIDR
network:
  version: 2
  renderer: networkd

  ethernets:
    IFACE0:
      dhcp4: false
      dhcp6: false
      optional: true
    IFACE1:
      dhcp4: false
      dhcp6: false
      optional: true

  bridges:
    cloudbr0:
      interfaces: [IFACE0]
      dhcp4: false
      dhcp6: false
      addresses:
        - PUBLIC_IP/PUBLIC_CIDR        # e.g., 203.0.113.10/24
      routes:
        - to: default
          via: PUBLIC_GW               # e.g., 203.0.113.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      parameters:
        stp: false
        forward-delay: 0

    cloudbr1:
      interfaces: [IFACE1]
      dhcp4: false
      dhcp6: false
      addresses:
        - SUBNET2_IP/SUBNET2_CIDR      # e.g., 10.50.0.2/24
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      parameters:
        stp: false
        forward-delay: 0
