# Netplan: 2 bridges, 1 subnet (IPv4 + IPv6 on cloudbr0, cloudbr1 is L2-only)
# Replace placeholders: IFACE0, IFACE1, PUBLIC_IP, PUBLIC_CIDR, PUBLIC_GW, PUBLIC_IPV6, PUBLIC_IPV6_GW
network:
  version: 2
  renderer: networkd

  ethernets:
    IFACE0:
      dhcp4: false
      dhcp6: false
      optional: true
    IFACE1:
      dhcp4: false
      dhcp6: false
      optional: true

  bridges:
    cloudbr0:
      interfaces: [IFACE0]
      dhcp4: false
      dhcp6: false
      addresses:
        - PUBLIC_IP/PUBLIC_CIDR        # e.g., 203.0.113.10/24
        - PUBLIC_IPV6/64               # e.g., 2001:db8:10::10/64
      routes:
        - to: default
          via: PUBLIC_GW               # e.g., 203.0.113.1
        - to: ::/0
          via: PUBLIC_IPV6_GW          # e.g., 2001:db8:10::1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8, 2606:4700:4700::1111]
      parameters:
        stp: false
        forward-delay: 0

    cloudbr1:
      interfaces: [IFACE1]
      dhcp4: false
      dhcp6: false
      # No IP addresses; L2-only bridge for CloudStack traffic
      parameters:
        stp: false
        forward-delay: 0
